cat gene.txt |cut -f1| xargs -I {} /project/wujp/zbs/nitrogen_gene_pipline2/final_pipeline/software/Rscript /project/wujp/zbs/nitrogen_gene_pipline2/final_pipeline/sub/alpha_rare_curve.R --input /project/wujp/zbs/Example_data/merge/{}/alpha/{}_alpha_rare.txt --design metadata.txt --group Group --output /project/wujp/zbs/Example_data/merge/{}/alpha/ --width 89 --height 59
cat gene.txt |cut -f1| xargs -I {} /project/wujp/zbs/nitrogen_gene_pipline2/final_pipeline/software/Rscript /project/wujp/zbs/nitrogen_gene_pipline2/final_pipeline/sub/alpha_boxplot.R --alpha_index richness --input /project/wujp/zbs/Example_data/merge/{}/alpha/{}_alpha_div.txt --design metadata.txt --group Group --output /project/wujp/zbs/Example_data/merge/{}/alpha/ --width 89 --height 59
cat gene.txt |cut -f1| xargs -I {} /project/wujp/zbs/nitrogen_gene_pipline2/final_pipeline/software/Rscript /project/wujp/zbs/nitrogen_gene_pipline2/final_pipeline/sub/alpha_boxplot.R --alpha_index chao1 --input /project/wujp/zbs/Example_data/merge/{}/alpha/{}_alpha_div.txt --design metadata.txt --group Group --output /project/wujp/zbs/Example_data/merge/{}/alpha/ --width 89 --height 59
cat gene.txt |cut -f1| xargs -I {} /project/wujp/zbs/nitrogen_gene_pipline2/final_pipeline/software/Rscript /project/wujp/zbs/nitrogen_gene_pipline2/final_pipeline/sub/alpha_boxplot.R --alpha_index shannon --input /project/wujp/zbs/Example_data/merge/{}/alpha/{}_alpha_div.txt --design metadata.txt --group Group --output /project/wujp/zbs/Example_data/merge/{}/alpha/ --width 89 --height 59
cat gene.txt |cut -f1| xargs -I {} /project/wujp/zbs/nitrogen_gene_pipline2/final_pipeline/software/Rscript /project/wujp/zbs/nitrogen_gene_pipline2/final_pipeline/sub/alpha_boxplot.R --alpha_index simpson --input /project/wujp/zbs/Example_data/merge/{}/alpha/{}_alpha_div.txt --design metadata.txt --group Group --output /project/wujp/zbs/Example_data/merge/{}/alpha/ --width 89 --height 59
cat gene.txt |cut -f1| xargs -I {} /project/wujp/zbs/nitrogen_gene_pipline2/final_pipeline/software/Rscript /project/wujp/zbs/nitrogen_gene_pipline2/final_pipeline/sub/alpha_boxplot.R --alpha_index invsimpson --input /project/wujp/zbs/Example_data/merge/{}/alpha/{}_alpha_div.txt --design metadata.txt --group Group --output /project/wujp/zbs/Example_data/merge/{}/alpha/ --width 89 --height 59
cat gene.txt |cut -f1| xargs -I {} /project/wujp/zbs/nitrogen_gene_pipline2/final_pipeline/software/Rscript /project/wujp/zbs/nitrogen_gene_pipline2/final_pipeline/sub/alpha_boxplot.R --alpha_index ACE --input /project/wujp/zbs/Example_data/merge/{}/alpha/{}_alpha_div.txt --design metadata.txt --group Group --output /project/wujp/zbs/Example_data/merge/{}/alpha/ --width 89 --height 59
cat gene.txt |cut -f1| xargs -I {} /project/wujp/zbs/nitrogen_gene_pipline2/final_pipeline/software/Rscript /project/wujp/zbs/nitrogen_gene_pipline2/final_pipeline/sub/beta_pcoa.R --input /project/wujp/zbs/Example_data/merge/{}/beta/bray_curtis.txt --design metadata.txt --group Group --output /project/wujp/zbs/Example_data/merge/{}/beta/bray_curtis.pcoa.pdf --width 89 --height 59 --label FALSE
cat gene.txt |cut -f1| xargs -I {} /project/wujp/zbs/nitrogen_gene_pipline2/final_pipeline/software/Rscript /project/wujp/zbs/nitrogen_gene_pipline2/final_pipeline/sub/tax_stackplot.R --input /project/wujp/zbs/Example_data/merge/{}/{}_merged_phylum_rpkm.csv --design metadata.txt --group Group --color Paired --legend 9 --output /project/wujp/zbs/Example_data/merge/{}/taxonomy/{}_phylum_rpkm --width 89 --height 95
cat gene.txt |cut -f1| xargs -I {} /project/wujp/zbs/nitrogen_gene_pipline2/final_pipeline/software/Rscript /project/wujp/zbs/nitrogen_gene_pipline2/final_pipeline/sub/tax_stackplot.R --input /project/wujp/zbs/Example_data/merge/{}/{}_merged_class_rpkm.csv --design metadata.txt --group Group --color Paired --legend 9 --output /project/wujp/zbs/Example_data/merge/{}/taxonomy/{}_class_rpkm --width 89 --height 95
cat gene.txt |cut -f1| xargs -I {} /project/wujp/zbs/nitrogen_gene_pipline2/final_pipeline/software/Rscript /project/wujp/zbs/nitrogen_gene_pipline2/final_pipeline/sub/tax_stackplot.R --input /project/wujp/zbs/Example_data/merge/{}/{}_merged_order_rpkm.csv --design metadata.txt --group Group --color Paired --legend 9 --output /project/wujp/zbs/Example_data/merge/{}/taxonomy/{}_order_rpkm --width 89 --height 95
cat gene.txt |cut -f1| xargs -I {} /project/wujp/zbs/nitrogen_gene_pipline2/final_pipeline/software/Rscript /project/wujp/zbs/nitrogen_gene_pipline2/final_pipeline/sub/tax_stackplot.R --input /project/wujp/zbs/Example_data/merge/{}/{}_merged_family_rpkm.csv --design metadata.txt --group Group --color Paired --legend 9 --output /project/wujp/zbs/Example_data/merge/{}/taxonomy/{}_family_rpkm --width 89 --height 95
cat gene.txt |cut -f1| xargs -I {} /project/wujp/zbs/nitrogen_gene_pipline2/final_pipeline/software/Rscript /project/wujp/zbs/nitrogen_gene_pipline2/final_pipeline/sub/tax_stackplot.R --input /project/wujp/zbs/Example_data/merge/{}/{}_merged_genus_rpkm.csv --design metadata.txt --group Group --color Paired --legend 9 --output /project/wujp/zbs/Example_data/merge/{}/taxonomy/{}_genus_rpkm --width 89 --height 95
cat gene.txt |cut -f1| xargs -I {} /project/wujp/zbs/nitrogen_gene_pipline2/final_pipeline/software/Rscript /project/wujp/zbs/nitrogen_gene_pipline2/final_pipeline/sub/tax_stackplot.R --input /project/wujp/zbs/Example_data/merge/{}/{}_merged_species_rpkm.csv --design metadata.txt --group Group --color Paired --legend 9 --output /project/wujp/zbs/Example_data/merge/{}/taxonomy/{}_species_rpkm --width 89 --height 95
cat gene.txt |cut -f1| xargs -I {} /project/wujp/zbs/nitrogen_gene_pipline2/final_pipeline/software/Rscript /project/wujp/zbs/nitrogen_gene_pipline2/final_pipeline/sub/gene_rpkm_boxplot.R --input /project/wujp/zbs/Example_data/merge/{}/{}_merged_rpkm.txt --group metadata.txt  --output /project/wujp/zbs/Example_data/merge/{}/{}_rpkm.pdf --width 160 --height 110
cat gene.txt |cut -f1| xargs -I {} /project/wujp/zbs/nitrogen_gene_pipline2/final_pipeline/software/Rscript /project/wujp/zbs/nitrogen_gene_pipline2/final_pipeline/sub/network_plot.R --input /project/wujp/zbs/Example_data/merge/{}/{}_otutab.txt --group metadata.txt  --output /project/wujp/zbs/Example_data/merge/{}/network --width 16 --height 11
